#!/bin/sh
cd ${0%/*} || exit 1    # run from this directory
allwmakeOptions='-allow-lib makeType' && . $WM_PROJECT_DIR/wmake/scripts/AllwmakeArguments
set -x

wmake $makeType specie
wmake $makeType solid
wmake $makeType thermophysicalFunctions
./properties/Allwmake $OriginalOptions

wmake $makeType basic
wmake $makeType reactionThermo
wmake $makeType laminarFlameSpeed
wmake $makeType chemistryModel
wmake $makeType barotropicCompressibilityModel
wmake $makeType thermalPorousZone
wmake $makeType SLGThermo

# Should be combined with solids&solidMixture
wmake $makeType basicSolidThermo
wmake $makeType solidChemistryModel

wmake $makeType radiationModels

# ----------------------------------------------------------------- end-of-file
