#!/bin/sh
cd ${0%/*} || exit 1    # run from this directory
allwmakeOptions='-allow-lib makeType' && . $WM_PROJECT_DIR/wmake/scripts/AllwmakeArguments

set -x

LES/Allwmake $OriginalOptions
incompressible/Allwmake $OriginalOptions
compressible/Allwmake $OriginalOptions
wmake $makeType derivedFvPatchFields

# ----------------------------------------------------------------- end-of-file
