#!/bin/sh
cd ${0%/*} || exit 1    # run from this directory
. $WM_PROJECT_DIR/wmake/scripts/AllwmakeArguments

if [ ! -d ${WM_THIRD_PARTY_DIR}/tecio ]
then
    echo "Did not find tecio in ${WM_THIRD_PARTY_DIR}. Not building foamToTecplot360."
else
    wmake
fi

# ----------------------------------------------------------------- end-of-file
