#!/bin/sh
cd ${0%/*} || exit 1    # run from this directory
. $WM_PROJECT_DIR/wmake/scripts/AllwmakeArguments
set -x

wmake
wmake SRFPimpleFoam
wmake pimpleDyMFoam

# ----------------------------------------------------------------- end-of-file
