#!/bin/sh
cd ${0%/*} || exit 1    # run from this directory
. $WM_PROJECT_DIR/wmake/scripts/AllwmakeArguments
set -x

wmake libso phaseModel
wmake libso interfacialModels
wmake libso kineticTheoryModels
wmake

# ----------------------------------------------------------------- end-of-file
