#!/bin/sh
cd ${0%/*} || exit 1    # run from this directory
allwmakeOptions='-allow-lib makeType' && . $WM_PROJECT_DIR/wmake/scripts/AllwmakeArguments
set -x

decompose/Allwmake $OriginalOptions
reconstruct/Allwmake $OriginalOptions
wmake $makeType distributed


# ----------------------------------------------------------------- end-of-file
