#!/bin/sh
cd ${0%/*} || exit 1    # run from this directory
allwmakeOptions='-allow-lib makeType' && . $WM_PROJECT_DIR/wmake/scripts/AllwmakeArguments
set -x

wmake $makeType distributionModels
wmake $makeType basic
wmake $makeType solidParticle
wmake $makeType intermediate
wmake $makeType spray
wmake $makeType dieselSpray
wmake $makeType dsmc
wmake $makeType coalCombustion

molecularDynamics/Allwmake $OriginalOptions

# ----------------------------------------------------------------- end-of-file
