#!/bin/sh
cd ${0%/*} || exit 1    # run from this directory
allwmakeOptions='-allow-readline readingMode' && . $WM_PROJECT_DIR/wmake/scripts/AllwmakeArguments

unset COMP_FLAGS LINK_FLAGS

#
# use readline if available
# unless otherwise specified (with NO_READLINE)
#
# eg,  ./Allwmake NO_READLINE
#

if [ -f /usr/include/readline/readline.h -a "${readingMode%NO_READLINE}" = "$readingMode" ]
then
    echo "Found <readline/readline.h>  --  enabling readline support."
    export COMP_FLAGS="-DHAS_READLINE"
    export LINK_FLAGS="-lreadline -lncurses"
fi

wmake

# ----------------------------------------------------------------- end-of-file
