#!/bin/sh
cd ${0%/*} || exit 1    # run from this directory
allwmakeOptions='-allow-lib makeType' && . $WM_PROJECT_DIR/wmake/scripts/AllwmakeArguments
set -x

wmakeLnInclude ../incompressible/LES

wmake $makeType LESfilters
wmake $makeType LESdeltas

# ----------------------------------------------------------------- end-of-file
