#!/bin/sh
cd ${0%/*} || exit 1    # run from this directory
allwmakeOptions='-allow-lib makeType' && . $WM_PROJECT_DIR/wmake/scripts/AllwmakeArguments
set -x

wmake $makeType liquidProperties
wmake $makeType liquidMixtureProperties
wmake $makeType solidProperties
wmake $makeType solidMixtureProperties


# ----------------------------------------------------------------- end-of-file
