#!/bin/sh
cd ${0%/*} || exit 1    # run from this directory
makeType=${1:-libso}
set -x

wmake $makeType scotchDecomp
wmake $makeType ptscotchDecomp
if [ "$makeType" != "lib" ]; then
  wmake $makeType metisDecomp
  wmake $makeType MGridGen
fi

# ----------------------------------------------------------------- end-of-file
